f(initial_spec) meet initial specifications
0804robot/State-machine pull request #2
Opened 2022-10-07 20:02 UTC by SammyOina

2022-10-09 15:40 UTC, 0x6f736f646f requested changes
Remove files that shouldn't be there`.vscode`, `workspace`, `.ini`

2022-10-14 19:53 UTC, 0x6f736f646f requested changes
Remove `workspace file`, `platform.ini` and `.vscode`

2022-10-14 20:24 UTC, 0x6f736f646f approved these changes

2022-10-14 21:38 UTC, Mike-Kimani approved these changes

2022-10-14 21:44 UTC, merged